### ISSUE TITLE
dagger injection fatal error, please help!

### ISSUE THREAD

**Issue by Inside4ndroid** [ahmedorabi94/Movies-TV-Shows-Guide#1]
hi when the app runs it force closes staright away with the following stacktrace any chance you can help in fixing this??

oh and you may note i converted the whole project to androidx just in case thats the cause?

EDIT: it only seems to happen when using a tablet or larger screen device.....???

Thank You :)

```
java.lang.IllegalArgumentException: No injector factory bound for Class<com.test.ahmedorabi.movieapp.view.ui.DetailActivityFragment>
        at dagger.android.DispatchingAndroidInjector.inject(DispatchingAndroidInjector.java:104)
        at dagger.android.support.AndroidSupportInjection.inject(AndroidSupportInjection.java:74)
        at com.test.ahmedorabi.movieapp.di.AppInjector$2.onFragmentCreated(AppInjector.java:82)
        at androidx.fragment.app.FragmentManagerImpl.dispatchOnFragmentCreated(FragmentManager.java:3496)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419)
        at androidx.fragment.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1195)
        at androidx.fragment.app.FragmentTransition.calculateFragments(FragmentTransition.java:1078)
        at androidx.fragment.app.FragmentTransition.startTransitions(FragmentTransition.java:117)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2408)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
        at androidx.fragment.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:951)
```

**Comment by ahmedorabi94** [comment]
try to change dagger version

**Comment by Inside4ndroid** [comment]
thank you :)
